### ISSUE TITLE
Pretendo - Game status not updating

### ISSUE THREAD

**Issue by Natino64** [MCMi460/3DS-RPC#43] opened 2024-10-06 21:40 UTC
Hi,

I have registered my console on 3dsrpc, alongside my discord account.

My 3DS is on pretendo, it's connected online, with game status sharing enabled in the friends menu. 

However, despite it being an extended period of time (15+ minutes) my discord status hasn't updated and my 3dsrpc profile claims I'm offline.

3DSRPC profile: https://3dsrpc.com/user/220765661960/?network=pretendo

I also notice the Delta friend (3DSRPC profile in my friends list) is listed as offline. Not sure if this has anything to do with it?

**Comment by Preloading** [comment] 2024-10-07 14:23
The 3ds being offline has nothing to do with it. It more than likely just crashed or hung

**Comment by Preloading** [comment] 2024-10-07 17:14
Also duplicate of #42

**Comment by spotlightishere** [comment] 2024-12-10 03:30
Closing this in favor of the aforementioned issue. We definitely have some issues here - thank you for reporting!

**Closed by spotlightishere** 2024-12-10 03:30 UTC
